spring:
  application:
    name: wkgmall-ware
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wkgmall_wms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 10000
